# Generated by Django 5.0.7 on 2025-02-23 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Jogo')),
                ('resumo', models.CharField(max_length=350, verbose_name='Descrição do Jogo')),
                ('html', models.TextField(blank=True, max_length=10000, null=True, verbose_name='HTML')),
                ('css', models.TextField(blank=True, max_length=10000, null=True, verbose_name='CSS')),
                ('js', models.TextField(blank=True, max_length=10000, null=True, verbose_name='JS')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Criador')),
                ('biografia', models.CharField(blank=True, max_length=350, null=True, verbose_name='Biografia do jogador')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos do jogador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendo_seguido', to='api.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quem_segue', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quem_curtiu', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
